Repository Busan-Dinosaur/FoodBowl-iOS, pull requests merged in 2023-08, with the labels that each got.

#104 [CHORE] 애플로그인 시 백엔드에 보내야 하는 값 확인(#103)
  FoodBowl/Screens/Sign/OnboardingViewController.swift
Labels: 🛠 Chore, 📬 API, 👾 하디

#108 [FEAT] 보안을 강화한 로그인 기능 구현
  FoodBowl.xcodeproj/project.pbxproj
  FoodBowl.xcodeproj/xcuserdata/coby.xcuserdatad/xcschemes/xcschememanagement.plist
  FoodBowl/Global/Extensions/MoyaProvider+Extensions.swift
  FoodBowl/Global/Extensions/String+Extension.swift
  FoodBowl/Global/Supports/Info.plist
  FoodBowl/Global/Supports/SceneDelegate.swift
  FoodBowl/Global/Utils/Configurations.swift
  FoodBowl/Global/Utils/KeychainManager.swift
  FoodBowl/Network/API/ServiceAPI.swift
  FoodBowl/Network/Request/SignRequest.swift
  FoodBowl/Network/Response/HttpsResponse.swift
  FoodBowl/Network/Response/PlaceResponse.swift
  FoodBowl/Network/Response/SignResponse.swift
  FoodBowl/Screens/NewFeed/View/SearchStoreViewController.swift
  FoodBowl/Screens/NewFeed/View/SetStoreViewController.swift
  FoodBowl/Screens/Profile/View/SettingViewController.swift
  FoodBowl/Screens/Sign/View/AgreementViewController.swift
  FoodBowl/Screens/Sign/View/OnboardingViewController.swift
  FoodBowl/Screens/Sign/View/SetProfileViewController.swift
  FoodBowl/Screens/Sign/ViewModel/SignViewModel.swift
Labels: ✨ Feature, 📬 API, 🔨 Refactor, 👾 코비

#110 [Cl] Build test를 하는 yml파일 추가 (#109)
  .github/workflows/Test_on_develop.yml
  FoodBowl.xcodeproj/project.pbxproj
Labels: 🤖 CI, 👾 하디
